services:
  redis:
    image: redis:7-alpine # Use a lightweight, stable image
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379" # Map port 6379 on the host to the container
    command: redis-server  

  player-service:
    build:
      context: ./player-service
      dockerfile: Dockerfile
    ports:
      - "5043:5043"
    volumes:
      - player-data:/app/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5043/players/1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  matchmaking-service:
    build:
      context: ./matchmaking-service
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

volumes:
  player-data:
